VALID_PAIRS = frozenset(
    {
        # sector - sub_sector
        ("Basic Materials", "Metals & Mining"),
        ("Basic Materials", "Chemicals"),
        ("Basic Materials", "Building Materials"),
        ("Basic Materials", "Paper & Forest Products"),
        ("Basic Materials", "Basic Materials - Diversified"),
        ("Communication Services", "Media & Entertainment"),
        ("Communication Services", "Telecom Services"),
        ("Consumer Cyclicals", "Automotive"),
        ("Consumer Cyclicals", "Retail"),
        ("Consumer Cyclicals", "Restaurants & Food Retail"),
        ("Consumer Cyclicals", "Hotels, Resorts & Leisure"),
        ("Consumer Cyclicals", "Furnishings, Fixtures & Appliances"),
        ("Consumer Cyclicals", "Luxury Goods"),
        ("Consumer Cyclicals", "Packaging & Containers"),
        ("Consumer Cyclicals", "Apparel & Accessories"),
        # ("Consumer Cyclicals", "Media & Entertainment"),
        ("Consumer Cyclicals", "Personal Services"),
        ("Consumer Defensive", "Food & Beverage Production"),
        ("Consumer Defensive", "Food Distribution"),
        ("Consumer Defensive", "Education & Training Services"),
        ("Consumer Non-Cyclicals", "Food & Beverage Retail & Production"),
        ("Energy", "Oil & Gas Operations & Services"),
        ("Energy", "Oil, Gas & Coal"),
        ("Financial Services", "Asset Management & Investment"),
        ("Financial Services", "Banks & Credit Services"),
        ("Financial Services", "Financial Data & Shell Companies"),
        ("Financial Services", "Insurance"),
        ("Healthcare", "Healthcare Facilities & Services"),
        ("Healthcare", "Pharmaceuticals & Research"),
        ("Healthcare", "Medical Devices & Supplies"),
        ("Industrials", "Engineering, Construction & Building Products"),
        ("Industrials", "Industrial Machinery & Parts"),
        # ("Industrials", "Transportation & Logistics"),
        ("Industrials", "Supply Chain, Freight & Infrastructure"),
        ("Industrials", "Business & Employment Services"),
        ("Industrials", "Conglomerates & Holdings"),
        ("Industrials", "Aerospace & Defense"),
        ("Industrials", "Waste Management & Pollution Control"),
        ("Industrials", "Rental, Leasing & Security Services"),
        ("Industrials", "Industrial Distribution"),
        ("Infrastructures", "Heavy Construction & Transport Infrastructure"),
        ("Infrastructures", "Telecommunication"),
        ("Properties & Real Estate", "Real Estate - Development"),
        ("Properties & Real Estate", "Real Estate Services"),
        ("Properties & Real Estate", "Real Estate - Diversified"),
        ("Properties & Real Estate", "Other Real Estate Operations"),
        ("REIT", "REIT - Industrial"),
        ("REIT", "REIT - Office"),
        ("REIT", "REIT - Diversified"),
        ("REIT", "REIT - Retail"),
        ("REIT", "REIT - Specialty & Healthcare"),
        ("Technology", "Hardware & Electronics"),
        ("Technology", "Software & IT Services"),
        ("Technology", "Semiconductors & Equipment"),
        ("Technology", "Communication & Instruments"),
        ("Transportation & Logistics", "Transportation & Logistics"),
        ("Utilities", "Utilities - Regulated"),
        ("Utilities", "Utilities - Renewable"),
        ("Utilities", "Utilities - Independent & Diversified"),
    }
)


SECTOR_REMAP = {
    "Financials": "Financial Services",
    "Transportation & Logistic": "Transportation & Logistics",
}


DIRECT_SUBSECTOR_MAP = {
    "Medical Distribution": ("Healthcare", "Medical Devices & Supplies"),
    "Oil, Gas & Coal": ("Energy", "Oil, Gas & Coal"),
    "Utilities - Diversified": ("Utilities", "Utilities - Independent & Diversified"),
    "Electronic Components": ("Technology", "Hardware & Electronics"),
    "REIT - Diversified": ("REIT", "REIT - Diversified"),
    "Software - Infrastructure": ("Technology", "Software & IT Services"),
    "Software - Application": ("Technology", "Software & IT Services"),
    "Electrical Equipment & Parts": ("Industrials", "Industrial Machinery & Parts"),
    "Insurance": ("Financial Services", "Insurance"),
    "Pharmaceutical Retailers": ("Healthcare", "Healthcare Facilities & Services"),
    "Internet Retail": ("Consumer Cyclicals", "Retail"),
    "Leisure": ("Consumer Cyclicals", "Hotels, Resorts & Leisure"),
    "Education & Training Services": ("Consumer Defensive", "Education & Training Services"),
    "Medical Devices": ("Healthcare", "Medical Devices & Supplies"),
    "Confectioners": ("Consumer Defensive", "Food & Beverage Production"),
    "Auto & Truck Dealerships": ("Consumer Cyclicals", "Automotive"),
    "Industrial Machinery & Equipment": ("Industrials", "Industrial Machinery & Parts"),
    "Paper & Paper Products": ("Basic Materials", "Paper & Forest Products"),
    "Capital Markets": ("Financial Services", "Asset Management & Investment"),
    "REIT - Industrial": ("REIT", "REIT - Industrial"),
    "Utilities - Independent Power Producers": ("Utilities", "Utilities - Independent & Diversified"),
    "Specialty Industrial Machinery": ("Industrials", "Industrial Machinery & Parts"),
    "Asset Management": ("Financial Services", "Asset Management & Investment"),
    "Automobiles & Components": ("Consumer Cyclicals", "Automotive"),
    "Resorts & Casinos": ("Consumer Cyclicals", "Hotels, Resorts & Leisure"),
    "Financial Data & Stock Exchanges": ("Financial Services", "Financial Data & Shell Companies"),
    "Lumber & Wood Production": ("Basic Materials", "Paper & Forest Products"),
    "Banks": ("Financial Services", "Banks & Credit Services"),
    "Medical Instruments & Supplies": ("Healthcare", "Medical Devices & Supplies"),
    "Auto Manufacturers": ("Consumer Cyclicals", "Automotive"),
    "Thermal Coal": ("Energy", "Oil, Gas & Coal"),
    "Furnishings, Fixtures & Appliances": ("Consumer Cyclicals", "Furnishings, Fixtures & Appliances"),
    "Utilities - Regulated Gas": ("Utilities", "Utilities - Regulated"),
    "Specialty Business Services": ("Industrials", "Business & Employment Services"),
    "Specialty Chemicals": ("Basic Materials", "Chemicals"),
    "Insurance - Property & Casualty": ("Financial Services", "Insurance"),
    "Other Industrial Metals & Mining": ("Basic Materials", "Metals & Mining"),
    "REIT - Retail": ("REIT", "REIT - Retail"),
    "Credit Services": ("Financial Services", "Banks & Credit Services"),
    "Multi-sector Holdings": ("Industrials", "Conglomerates & Holdings"),
    "Packaging & Containers": ("Consumer Cyclicals", "Packaging & Containers"),
    "Real Estate - Diversified": ("Properties & Real Estate", "Real Estate - Diversified"),
    "Medical Care Facilities": ("Healthcare", "Healthcare Facilities & Services"),
    "Real Estate Services": ("Properties & Real Estate", "Real Estate Services"),
    "Utilities - Regulated Water": ("Utilities", "Utilities - Regulated"),
    "Luxury Goods": ("Consumer Cyclicals", "Luxury Goods"),
    "Oil & Gas E&P": ("Energy", "Oil & Gas Operations & Services"),
    "Department Stores": ("Consumer Cyclicals", "Retail"),
    "Staffing & Employment Services": ("Industrials", "Business & Employment Services"),
    "Specialty Retail": ("Consumer Cyclicals", "Retail"),
    "Real Estate - Development": ("Properties & Real Estate", "Real Estate - Development"),
    "Engineering & Construction": ("Industrials", "Engineering, Construction & Building Products"),
    "REIT - Office": ("REIT", "REIT - Office"),
    "Apparel Manufacturing": ("Consumer Cyclicals", "Apparel & Accessories"),
    "Steel": ("Basic Materials", "Metals & Mining"),
    "Restaurants & Bars": ("Consumer Cyclicals", "Restaurants & Food Retail"),
    "Conglomerates": ("Industrials", "Conglomerates & Holdings"),
    "Lodging": ("Consumer Cyclicals", "Hotels, Resorts & Leisure"),
    "Chemicals": ("Basic Materials", "Chemicals"),
    "Metal Fabrication": ("Industrials", "Industrial Machinery & Parts"),
    "Diagnostics & Research": ("Healthcare", "Pharmaceuticals & Research"),
    "Oil & Gas Midstream": ("Energy", "Oil & Gas Operations & Services"),
    "Building Products & Equipment": ("Industrials", "Engineering, Construction & Building Products"),
    "Computer Hardware": ("Technology", "Hardware & Electronics"),
    "Apparel Retail": ("Consumer Cyclicals", "Apparel & Accessories"),
    "Restaurants": ("Consumer Cyclicals", "Restaurants & Food Retail"),
    "Personal Services": ("Consumer Cyclicals", "Personal Services"),
    "Waste Management": ("Industrials", "Waste Management & Pollution Control"),
    "Health Information Services": ("Healthcare", "Healthcare Facilities & Services"),
    "Business Equipment & Supplies": ("Industrials", "Business & Employment Services"),
    "Pollution & Treatment Controls": ("Industrials", "Waste Management & Pollution Control"),
    "Integrated Oil": ("Energy", "Oil & Gas Operations & Services"),
    "Oil & Gas Refining & Marketing": ("Energy", "Oil & Gas Operations & Services"),
    "REIT - Specialty": ("REIT", "REIT - Specialty & Healthcare"),
    "Packaged Foods": ("Consumer Defensive", "Food & Beverage Production"),
    "REIT - Healthcare Facilities": ("REIT", "REIT - Specialty & Healthcare"),
    "Utilities - Renewable": ("Utilities", "Utilities - Renewable"),
    "Pharmaceuticals & Health Care Research": ("Healthcare", "Pharmaceuticals & Research"),
    "Gold": ("Basic Materials", "Metals & Mining"),
    "Building Materials": ("Basic Materials", "Building Materials"),
    "Security & Protection Services": ("Industrials", "Rental, Leasing & Security Services"),
    "Auto Parts": ("Consumer Cyclicals", "Automotive"),
    "Technology Hardware & Equipment": ("Technology", "Hardware & Electronics"),
    "Mortgage Finance": ("Financial Services", "Banks & Credit Services"),
    "Shell Companies": ("Financial Services", "Financial Data & Shell Companies"),
    "Farm Products": ("Consumer Defensive", "Food & Beverage Production"),
    "Communication Equipment": ("Technology", "Communication & Instruments"),
    "Oil & Gas Equipment & Services": ("Energy", "Oil & Gas Operations & Services"),
    "Aerospace & Defense": ("Industrials", "Aerospace & Defense"),
    "Investment Service": ("Financial Services", "Asset Management & Investment"),
    "Drug Manufacturers - Specialty & Generic": ("Healthcare", "Pharmaceuticals & Research"),
    "Industrial Distribution": ("Industrials", "Industrial Distribution"),
    "Aluminum": ("Basic Materials", "Metals & Mining"),
    "Information Technology Services": ("Technology", "Software & IT Services"),
    "Beverages - Non-Alcoholic": ("Consumer Defensive", "Food & Beverage Production"),
    "Consulting Services": ("Industrials", "Business & Employment Services"),
    "Rental & Leasing Services": ("Industrials", "Rental, Leasing & Security Services"),
    "Semiconductor Equipment & Materials": ("Technology", "Semiconductors & Equipment"),
    "Healthcare Equipment & Providers": ("Healthcare", "Healthcare Facilities & Services"),
    "Semiconductors": ("Technology", "Semiconductors & Equipment"),
    "Apparel & Accessories Retailers": ("Consumer Cyclicals", "Apparel & Accessories"),
    "Marine Fishing & Aquaculture": ("Consumer Defensive", "Food & Beverage Production"),
    "Seafood Sourcing & Distribution": ("Consumer Defensive", "Food Distribution"),
    "Hospitality REITs (Hotels)": ("REIT", "REIT - Specialty & Healthcare"),
    "Communications & Networking Infrastructure": ("Technology", "Communication & Instruments"),
    "Shipbuilding & Marine Engineering": ("Industrials", "Industrial Machinery & Parts"),
    "Offshore Oil & Gas Services": ("Energy", "Oil & Gas Operations & Services"),
    "Furniture Manufacturing & Retail": ("Consumer Cyclicals", "Furnishings, Fixtures & Appliances"),
    "Real Estate Management & Development": ("Properties & Real Estate", "Real Estate - Development"),
}


SECONDARY_PAIR_MAP = {
    # Media & Entertainment family: target sub stays "Media & Entertainment",
    ("Communication Services", "Entertainment"): ("Communication Services", "Media & Entertainment"),
    ("Consumer Cyclicals", "Entertainment"): ("Consumer Cyclicals", "Hotels, Resorts & Leisure"),
    ("Communication Services", "Publishing"): ("Communication Services", "Media & Entertainment"),
    ("Consumer Cyclicals", "Publishing"): ("Consumer Cyclicals", "Hotels, Resorts & Leisure"),
    ("Communication Services", "Advertising Agencies"): ("Communication Services", "Media & Entertainment"),
    ("Consumer Cyclicals", "Advertising Agencies"): ("Consumer Cyclicals", "Hotels, Resorts & Leisure"),
    ("Communication Services", "Electronic Gaming & Multimedia"): ("Communication Services", "Media & Entertainment"),
    ("Consumer Cyclicals", "Electronic Gaming & Multimedia"): ("Consumer Cyclicals", "Hotels, Resorts & Leisure"),

    # Telecom family.
    ("Infrastructures", "Telecom Services"): ("Infrastructures", "Telecommunication"),
    ("Communication Services", "Telecommunication"): ("Communication Services", "Telecom Services"),
    # ("Communication Services", "Telecom Services") and
    # ("Infrastructures", "Telecommunication") are already valid pairs.
 
    # Transportation: target sub is "Transportation & Logistics",
    # sector stays Industrials or the standalone Transportation & Logistics.
    ("Industrials", "Transportation"): ("Industrials", "Supply Chain, Freight & Infrastructure"),
    ("Transportation & Logistics", "Transportation"): ("Transportation & Logistics", "Transportation & Logistics"),
    ("Industrials", "Other Transportation"): ("Industrials", "Supply Chain, Freight & Infrastructure"),
    ("Transportation & Logistics", "Other Transportation"): ("Transportation & Logistics", "Transportation & Logistics"),
    ("Industrials", "Marine Shipping"): ("Industrials", "Supply Chain, Freight & Infrastructure"),
    ("Transportation & Logistics", "Marine Shipping"): ("Transportation & Logistics", "Transportation & Logistics"),
    ("Industrials", "Railroads"): ("Industrials", "Supply Chain, Freight & Infrastructure"),
    ("Transportation & Logistics", "Railroads"): ("Transportation & Logistics", "Transportation & Logistics"),
    ("Industrials", "Integrated Freight & Logistics"): ("Industrials", "Supply Chain, Freight & Infrastructure"),
    ("Transportation & Logistics", "Integrated Freight & Logistics"): ("Transportation & Logistics", "Transportation & Logistics"),
    ("Industrials", "Logistics & Deliveries"): ("Industrials", "Supply Chain, Freight & Infrastructure"),
    ("Transportation & Logistics", "Logistics & Deliveries"): ("Transportation & Logistics", "Transportation & Logistics"),

    # Transportation Infrastructure: Infrastructures vs Industrials/Transport.
     ("Infrastructures", "Transportation Infrastructure"): ("Infrastructures", "Heavy Construction & Transport Infrastructure"),
    ("Industrials", "Transportation Infrastructure"): ("Industrials", "Supply Chain, Freight & Infrastructure"),
    ("Transportation & Logistics", "Transportation Infrastructure"): ("Transportation & Logistics", "Transportation & Logistics"),
 
    # Heavy Constructions & Civil Engineering.
    ("Industrials", "Heavy Constructions & Civil Engineering"): ("Industrials", "Engineering, Construction & Building Products"),
    ("Infrastructures", "Heavy Constructions & Civil Engineering"): ("Infrastructures", "Heavy Construction & Transport Infrastructure"),
 
    # Infrastructure Operations (only Infrastructures sub that fits).
    ("Infrastructures", "Infrastructure Operations"): ("Infrastructures", "Heavy Construction & Transport Infrastructure"),
 
    # Food. Consumer Defensive vs Consumer Non-Cyclicals.
    ("Consumer Defensive", "Food & Beverage"): ("Consumer Defensive", "Food & Beverage Production"),
    ("Consumer Non-Cyclicals", "Food & Beverage"): ("Consumer Non-Cyclicals", "Food & Beverage Retail & Production"),
    ("Consumer Non-Cyclicals", "Food Distribution"): ("Consumer Non-Cyclicals", "Food & Beverage Retail & Production"),
    ("Consumer Defensive", "Food & Staples Retailing"): ("Consumer Defensive", "Food Distribution"),
    ("Consumer Non-Cyclicals", "Food & Staples Retailing"): ("Consumer Non-Cyclicals", "Food & Beverage Retail & Production"),
    # ("Consumer Defensive", "Food Distribution") already valid.
 
    # Investment Holding Companies: Financial vs Industrials.
    ("Financial Services", "Investment Holding Companies"): ("Financial Services", "Asset Management & Investment"),
    ("Industrials", "Investment Holding Companies"): ("Industrials", "Conglomerates & Holdings"),
 
    # Scientific & Technical Instruments: Technology vs Healthcare.
    ("Technology", "Scientific & Technical Instruments"): ("Technology", "Communication & Instruments"),
    ("Healthcare", "Scientific & Technical Instruments"): ("Healthcare", "Medical Devices & Supplies"),
 
    # Electronics & Computer Distribution: Technology vs Industrials.
    ("Technology", "Electronics & Computer Distribution"): ("Technology", "Hardware & Electronics"),
    ("Industrials", "Electronics & Computer Distribution"): ("Industrials", "Industrial Distribution"),
 
    # Farm & Heavy Construction Machinery: default to Industrial Machinery.
    ("Industrials", "Farm & Heavy Construction Machinery"): ("Industrials", "Industrial Machinery & Parts"),
 
    # Tools & Accessories: default to Industrial Machinery when Industrials.
    ("Industrials", "Tools & Accessories"): ("Industrials", "Industrial Machinery & Parts"),

    ("REIT", "REIT - Hotel & Motel"): ("REIT", "REIT - Specialty & Healthcare"),
    ("Basic Materials", "Basic Materials"): ("Basic Materials", "Basic Materials - Diversified")
}