name: Update daily data of sgx_companies and klse_companies

on:
  schedule:
      - cron: '0 18 * * *' # run at 06.00 PM everyday
  workflow_dispatch:

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: execute SG update process
        env:
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
            PROXY: ${{ secrets.PROXY }}
        run: |
          python sg_my_scraper.py -sg -d

      - name: execute MY update process
        env:
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
            PROXY: ${{ secrets.PROXY }}
        run: |
          python sg_my_scraper.py -my -d
