name: Update sgx_klse weekly financial data (dividend_ttm) from yahoo finance

on:
  schedule:
    - cron: '0 11 * * 1-5' # Run every monday at 8am (Western Indonesia Time)
  
  workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 # Replace with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r yf_requirements.txt
    - name: Run Python Script SGX
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python financial_data_yf.py MY weekly
    
    - name: Run Python Script SGX
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python financial_data_yf.py SG weekly
   
    - name: commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        branch: main 
