name: Update sgx_companies and klse_companies monthly data

on:
  schedule:
      - cron: '0 0 1 * *' # run at 1st day of every month at 12:00 AM
  workflow_dispatch:

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute sg_my_scraper.py script
        env:
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
            PROXY: ${{ secrets.PROXY }}
        run: |
          python sg_my_scraper.py -sg -m
          python sg_my_scraper.py -my -m
