name: SGX Company Public Date Update
on:
  schedule:
    - cron: "0 0 */14 * *"   # Every 2 weeks at midnight UTC
jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run SGX updater script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python sgx_scrape/public_date_updater.py
